---
# Install Logstash indexer init script
- name: "Install Logstash indexer init script"
  action: template src=logstash_indexer.j2 dest=/etc/init.d/{{ logstash.indexer.service }} owner=root group=root mode=0755
  when: with_indexer
  notify:
    - "Enable Logstash indexer"
    - "Restart Logstash indexer"

# Install Logstash shipper init script
- name: "Install Logstash shipper init script"
  action: template src=logstash_shipper.j2 dest=/etc/init.d/{{ logstash.shipper.service }} owner=root group=root mode=0755
  when: with_shipper
  notify:
    - "Enable Logstash shipper"
    - "Restart Logstash shipper"

# Install Logstash indexer config
- name: "Install Logstash indexer config"
  sudo: yes
  action: template src=logstash_indexer.conf.j2 dest={{ logstash.indexer.conf }} owner=root group=root mode=0755
  when: with_indexer
  notify:
    - "Enable Logstash indexer"
    - "Restart Logstash indexer"

# Install Logstash shipper config
- name: "Install Logstash shipper config"
  sudo: yes
  action: template src=logstash_shipper.conf.j2 dest={{ logstash.shipper.conf }} owner=root group=root mode=0755
  when: with_shipper
  register: shipper_config
  notify:
    - "Restart Logstash shipper"

# Install Logstash init script
# - name: "Install Logstash web init script"
#   template: src=templates/logstash_web.j2 dest=/etc/init.d/${logstash.service} owner=root group=root mode=0755
#   when_boolean: ${with_web}
#   tags:
#     - logstash