---
- name: "Install Logstash dependencies"
  sudo: yes
  action: "{{ansible_pkg_mgr}} pkg={{ item }} state=installed"
  with_items: logstash.{{ansible_pkg_mgr}}.dependencies

- name: "Create Logstash directories"
  sudo: yes
  action: file path={{ item }} group=root owner=root mode=0755 state=directory
  with_items:
    - '{{ logstash.dir }}'
    - '{{ logstash.dir }}/bin'
    - '{{ logstash.dir }}/etc'

- name: "Prepare startupscripts"
  include: initscripts.yml
  when: logstash_start == 'initscripts'

- name: "Prepare upstartscripts"
  include: upstart.yml
  when: logstash_start == 'upstart'

- name: "Fetch Logstash.jar"
  sudo: yes
  get_url: url={{ logstash.url }}/{{ logstash.jar }} dest={{ logstash.dir }}/bin/{{ logstash.jar }}
           mode=0440 sha256sum={{ logstash.sha256 }}
  register: got_jar

- name: "Start Logstash indexer"
  action: service name={{ logstash.indexer.service }} state=started
  when: with_indexer

- name: "Start Logstash shipper"
  action: service name={{ logstash.shipper.service }} state=started
  when: with_shipper

- name: "Link logstash /etc"
  file: src={{ logstash.conf }} dest=/etc/logstash state=link
