---
- name: "Install Logstash dependencies"
  action: "{{ansible_pkg_mgr}} pkg={{ item }} state=installed"
  with_items: logstash.{{ansible_pkg_mgr}}.dependencies

- name: "Create Logstash directories"
  action: file path={{ item }} group=root owner=root mode=0755 state=directory
  with_items:
    - '{{ logstash.dir }}'
    - '{{ logstash.dir }}/bin'
    - '{{ logstash.dir }}/etc'

- name: "Fetch Logstash.tar.gz"
  get_url: url={{ logstash.url }}/{{ logstash.tar }} dest={{ logstash.dir }}/{{ logstash.tar }}
           mode=0440 sha256sum={{logstash.sha256}}
  register: got_tar

- name: "Extract logstash"
  command: chdir={{logstash.dir}} creates=README.md
           tar xfz {{ logstash.tar }} --strip-components=1

- name: "Prepare startupscripts"
  include: initscripts.yml
  when: logstash_start == 'initscripts'

- name: "Prepare upstartscripts"
  include: upstart.yml
  when: logstash_start == 'upstart'

- name: "Start Logstash indexer"
  service: name={{ logstash.indexer.service }} state=started
  when: with_indexer

- name: "Start Logstash shipper"
  service: name={{ logstash.shipper.service }} state=started
  when: with_shipper

- name: "Link logstash /etc"
  file: src={{ logstash.conf }} dest=/etc/logstash state=link
