---
- name: Create logstash user
  user: name=logstash home={{ logstash.dir }} system=yes state=present

- name: "Install Logstash indexer upstart config"
  template: src=logstash_indexer.upstart.j2 dest=/etc/init/{{ logstash.indexer.service }}.conf
          owner=root group=root mode=0644
  when: with_indexer
  notify:
      - "Reload upstart"

- name: Install logstash upstart wrapper
  template: src=logstash-wrapper.sh.j2 dest={{logstash.dir}}/bin/logstash-wrapper
            mode=0744 owner=logstash

- name: "Install Logstash shipper upstart config"
  template: src=logstash_shipper.upstart.j2
            dest=/etc/init/{{ logstash.shipper.service }}.conf
            owner=root group=root mode=0644
  when: with_shipper
  notify:
      - "Reload upstart"

- name: "Install Logstash indexer config"
  template: src=logstash_indexer.conf.j2 dest={{ logstash.indexer.conf }}
      owner=root group=root mode=0644
  when: with_indexer
  notify:
    - "Restart Logstash indexer"

- name: "Install Logstash shipper config"
  action: template src=logstash_shipper.conf.j2 dest={{ logstash.shipper.conf }}
        owner=root group=root mode=0644
  when: with_shipper
  register: shipper_config
  notify:
    - "Restart Logstash shipper"